import pandas as pd
import snowflake.connector
import os

EXCEL_PATH = '/Users/sweingartner/CoCo/AgedCare/Confidential/DRI/data/De-identified - 871 - Integration.xlsx'

def get_connection():
    return snowflake.connector.connect(
        connection_name=os.getenv("SNOWFLAKE_CONNECTION_NAME") or "dri"
    )

def setup_database():
    conn = get_connection()
    cur = conn.cursor()
    
    cur.execute("USE DATABASE AGEDCARE")
    cur.execute("USE SCHEMA AGEDCARE")
    cur.execute("USE WAREHOUSE MYWH")
    
    ddl_statements = """
-- Source Tables (Static versions for POC demo data)
CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.ACTIVE_RESIDENT_MEDICAL_PROFILE (
    RESIDENT_ID NUMBER NOT NULL,
    EVENT_DATE TIMESTAMP_NTZ,
    SPECIAL_NEEDS VARCHAR(16777216),
    ENTERED_BY_USER VARCHAR(256),
    ALLERGIES VARCHAR(16777216),
    ALLERGY_NOTES VARCHAR(16777216),
    ALLERGY_EXCLUSION VARCHAR(256),
    HAS_UNCODED_ALLERGIES BOOLEAN,
    HAS_GLUTEN_INTOLERANCE BOOLEAN,
    DIET VARCHAR(256),
    USUAL_BOWEL_PATTERN VARCHAR(256),
    HEIGHT NUMBER(10,2),
    WEIGHT_UPON_ADMISSION NUMBER(10,2),
    SYSTEM_KEY VARCHAR(256),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.ACTIVE_RESIDENT_ASSESSMENT_FORMS (
    BATCH_ID NUMBER NOT NULL,
    RESIDENT_ID NUMBER NOT NULL,
    EVENT_DATE TIMESTAMP_NTZ,
    FORM_ID NUMBER,
    FORM_NAME VARCHAR(512),
    ELEMENT_NO NUMBER,
    ELEMENT_NAME VARCHAR(1024),
    ELEMENT_TYPE VARCHAR(64),
    REPORT_CODE VARCHAR(64),
    QUESTION_CODE VARCHAR(64),
    ITEM_CODE VARCHAR(64),
    ITEM_NAME VARCHAR(512),
    RESPONSE VARCHAR(16777216),
    RESPONSE_OTHER VARCHAR(16777216),
    ENTERED_BY_USER VARCHAR(256),
    SYSTEM_KEY VARCHAR(256),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.ACTIVE_RESIDENT_MEDICATION (
    RESIDENT_ID NUMBER NOT NULL,
    MED_ID NUMBER,
    MED_NAME VARCHAR(512),
    MED_ROUTE VARCHAR(32),
    MED_STATUS VARCHAR(32),
    MED_START_DATE DATE,
    MED_END_DATE TIMESTAMP_NTZ,
    UPDATED_DATE TIMESTAMP_NTZ,
    SYSTEM_KEY VARCHAR(256),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.ACTIVE_RESIDENT_NOTES (
    PROGRESS_NOTE_ID NUMBER NOT NULL,
    PROGRESS_NOTE_TYPE VARCHAR(64),
    ADDITIONAL_NOTE_ID NUMBER,
    RESIDENT_ID NUMBER NOT NULL,
    EVENT_DATE TIMESTAMP_NTZ,
    PROGRESS_NOTE VARCHAR(16777216),
    ENTERED_BY_USER VARCHAR(256),
    NOTE_TYPE VARCHAR(64),
    SYSTEM_KEY VARCHAR(256),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.ACTIVE_RESIDENT_OBSERVATIONS (
    RESIDENT_ID NUMBER NOT NULL,
    CHART_NAME VARCHAR(256),
    OBSERVATION_GROUP_ID NUMBER,
    OBSERVATION_ID NUMBER,
    EVENT_DATE TIMESTAMP_NTZ,
    CHART_SECTION VARCHAR(256),
    CHART_LABEL VARCHAR(256),
    OBSERVATION_VALUE VARCHAR(1024),
    ENTERED_BY_USER VARCHAR(256),
    SYSTEM_KEY VARCHAR(256),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.ACTIVE_RESIDENT_OBSERVATION_GROUP (
    OBSERVATION_GROUP_ID NUMBER NOT NULL,
    CHART_TEMPLATE_ID NUMBER,
    CHART_NAME VARCHAR(256),
    RESIDENT_ID NUMBER NOT NULL,
    OBSERVATION_STATUS VARCHAR(32),
    OBSERVATION_TYPE VARCHAR(256),
    OBSERVATION_LOCATION VARCHAR(256),
    EVENT_DATE TIMESTAMP_NTZ,
    OBSERVATION_DESCRIPTION VARCHAR(16777216),
    ENTERED_BY_USER VARCHAR(256),
    SYSTEM_KEY VARCHAR(256),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- DRI Output Tables
CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_DEFICIT_DETAIL (
    RESIDENT_ID NUMBER NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DEFICIT_ID VARCHAR(64) NOT NULL,
    RULE_NUMBER NUMBER,
    RULE_DESCRIPTION VARCHAR(16777216),
    SOURCE_ID VARCHAR(64),
    SOURCE_TABLE VARCHAR(256),
    SOURCE_TYPE VARCHAR(256),
    RESULT VARCHAR(16777216),
    ENTERED_BY_USER VARCHAR(256),
    EVENT_DATE DATE,
    RULE_STATUS VARCHAR(32),
    EXPIRY_DAYS NUMBER,
    CLIENT_NAME VARCHAR(256)
) CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_DEFICIT_STATUS (
    RESIDENT_ID NUMBER NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DEFICIT_ID VARCHAR(64) NOT NULL,
    DEFICIT_STATUS VARCHAR(32),
    DEFICIT_START_DATE DATE,
    DEFICIT_EXPIRY_DATE DATE,
    DEFICIT_LAST_OCCURRENCE DATE,
    RULE_NUMBER NUMBER
) CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_DEFICIT_SUMMARY (
    RESIDENT_ID NUMBER NOT NULL,
    LOAD_TIMESTAMP TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    DRI_SCORE NUMBER(5,4),
    SEVERITY_BAND VARCHAR(64)
) CHANGE_TRACKING = TRUE;

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_SEVERITY (
    DRI_SEVERITY_ID NUMBER NOT NULL,
    DRI_SEVERITY_NAME VARCHAR(64),
    DRI_SEVERITY_MINIMUM_VALUE NUMBER(5,4),
    DRI_SEVERITY_MAXIMUM_VALUE NUMBER(5,4)
);

-- New Intelligence Tables
CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_LLM_ANALYSIS (
    ANALYSIS_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    RESIDENT_ID NUMBER NOT NULL,
    CLIENT_SYSTEM_KEY VARCHAR(256),
    ANALYSIS_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODEL_USED VARCHAR(64),
    PROMPT_VERSION VARCHAR(32),
    CLIENT_CONFIG_VERSION VARCHAR(32),
    RAW_RESPONSE VARIANT,
    PROCESSING_TIME_MS NUMBER,
    BATCH_RUN_ID VARCHAR(36),
    PRIMARY KEY (ANALYSIS_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_REVIEW_QUEUE (
    QUEUE_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    ANALYSIS_ID VARCHAR(36),
    RESIDENT_ID NUMBER NOT NULL,
    CLIENT_SYSTEM_KEY VARCHAR(256),
    CURRENT_DRI_SCORE NUMBER(5,4),
    PROPOSED_DRI_SCORE NUMBER(5,4),
    CURRENT_SEVERITY_BAND VARCHAR(64),
    PROPOSED_SEVERITY_BAND VARCHAR(64),
    INDICATORS_ADDED NUMBER,
    INDICATORS_REMOVED NUMBER,
    INDICATOR_CHANGES_JSON VARIANT,
    CHANGE_SUMMARY VARCHAR(16777216),
    STATUS VARCHAR(32) DEFAULT 'PENDING',
    REVIEWER_USER VARCHAR(256),
    REVIEWER_NOTES VARCHAR(16777216),
    EXCLUDED_INDICATORS VARIANT,
    REVIEW_TIMESTAMP TIMESTAMP_NTZ,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (QUEUE_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_CLIENT_CONFIG (
    CONFIG_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    CLIENT_SYSTEM_KEY VARCHAR(256) NOT NULL,
    CLIENT_NAME VARCHAR(256),
    DESCRIPTION VARCHAR(16777216),
    CONFIG_JSON VARIANT,
    VERSION VARCHAR(32),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_BY VARCHAR(256),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    MODIFIED_BY VARCHAR(256),
    MODIFIED_TIMESTAMP TIMESTAMP_NTZ,
    PRIMARY KEY (CONFIG_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_CLIENT_FORM_MAPPINGS (
    MAPPING_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    CLIENT_SYSTEM_KEY VARCHAR(256) NOT NULL,
    SOURCE_TABLE VARCHAR(256) NOT NULL,
    FORM_IDENTIFIER VARCHAR(256),
    FIELD_NAME VARCHAR(256) NOT NULL,
    MAPPED_INDICATOR VARCHAR(64),
    MAPPING_TYPE VARCHAR(32),
    MAPPING_RULES VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    NOTES VARCHAR(16777216),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MAPPING_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_CLIENT_INDICATOR_OVERRIDES (
    OVERRIDE_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    CLIENT_SYSTEM_KEY VARCHAR(256) NOT NULL,
    INDICATOR_ID VARCHAR(64) NOT NULL,
    OVERRIDE_TYPE VARCHAR(32) NOT NULL,
    OVERRIDE_VALUE VARIANT,
    REASON VARCHAR(16777216),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (OVERRIDE_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_PROMPT_VERSIONS (
    PROMPT_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    VERSION_NUMBER VARCHAR(32),
    PROMPT_TEXT VARCHAR(16777216),
    DESCRIPTION VARCHAR(16777216),
    CREATED_BY VARCHAR(256),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (PROMPT_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_RAG_INDICATORS (
    INDICATOR_ID VARCHAR(64) NOT NULL,
    DEFICIT_ID VARCHAR(64),
    INDICATOR_NAME VARCHAR(256),
    DEFINITION VARCHAR(16777216),
    KEYWORDS VARIANT,
    INCLUSION_CRITERIA VARCHAR(16777216),
    EXCLUSION_CRITERIA VARCHAR(16777216),
    TEMPORAL_TYPE VARCHAR(32),
    DEFAULT_EXPIRY_DAYS NUMBER,
    EXAMPLES VARIANT,
    PRIMARY KEY (INDICATOR_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_RAG_DECISIONS (
    DECISION_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    DEFICIT_ID VARCHAR(64),
    SOURCE_TEXT VARCHAR(16777216),
    DECISION VARCHAR(32),
    REASONING VARCHAR(16777216),
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DECISION_ID)
);

CREATE OR REPLACE TABLE AGEDCARE.AGEDCARE.DRI_AUDIT_LOG (
    LOG_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    EVENT_TYPE VARCHAR(64),
    RESIDENT_ID NUMBER,
    USER_NAME VARCHAR(256),
    EVENT_DETAILS VARIANT,
    CREATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (LOG_ID)
);
"""
    
    for stmt in ddl_statements.split(';'):
        stmt = stmt.strip()
        if stmt and not stmt.startswith('--'):
            print(f"Executing: {stmt[:60]}...")
            cur.execute(stmt)
    
    print("All tables created successfully!")
    
    cur.execute("""
INSERT INTO AGEDCARE.AGEDCARE.DRI_SEVERITY VALUES
(1, 'Low', 0.0000, 0.2000),
(2, 'Medium', 0.2001, 0.4000),
(3, 'High', 0.4001, 0.6000),
(4, 'Very High', 0.6001, 1.0000)
""")
    print("Severity bands inserted!")
    
    conn.close()

def load_demo_data():
    print(f"Loading demo data from {EXCEL_PATH}")
    
    xls = pd.ExcelFile(EXCEL_PATH)
    print(f"Available sheets: {xls.sheet_names}")
    
    sheet_table_map = {
        'ACTIVE_RESIDENT_MEDICAL_PROFILE': 'ACTIVE_RESIDENT_MEDICAL_PROFILE',
        'ACTIVE_RESIDENT_ASSESSMENT_FORM': 'ACTIVE_RESIDENT_ASSESSMENT_FORMS',
        'ACTIVE_RESIDENT_MEDICATION': 'ACTIVE_RESIDENT_MEDICATION',
        'ACTIVE_RESIDENT_NOTES': 'ACTIVE_RESIDENT_NOTES',
        'ACTIVE_RESIDENT_OBSERVATIONS': 'ACTIVE_RESIDENT_OBSERVATIONS',
        'ACTIVE_RESIDENT_OBSERVATION_GRO': 'ACTIVE_RESIDENT_OBSERVATION_GROUP'
    }
    
    conn = get_connection()
    cur = conn.cursor()
    cur.execute("USE DATABASE AGEDCARE")
    cur.execute("USE SCHEMA AGEDCARE")
    cur.execute("USE WAREHOUSE MYWH")
    
    from snowflake.connector.pandas_tools import write_pandas
    
    for sheet_name, table_name in sheet_table_map.items():
        if sheet_name in xls.sheet_names:
            print(f"\nLoading {sheet_name} -> {table_name}")
            df = pd.read_excel(EXCEL_PATH, sheet_name=sheet_name)
            df.columns = [c.upper().replace(' ', '_') for c in df.columns]
            print(f"  Columns: {list(df.columns)}")
            print(f"  Rows: {len(df)}")
            
            cur.execute(f"TRUNCATE TABLE IF EXISTS AGEDCARE.AGEDCARE.{table_name}")
            
            success, nchunks, nrows, _ = write_pandas(
                conn, df, table_name, 
                database='AGEDCARE', schema='AGEDCARE',
                auto_create_table=False
            )
            print(f"  Loaded {nrows} rows")
        else:
            print(f"Sheet {sheet_name} not found!")
    
    conn.close()
    print("\nDemo data loaded successfully!")

if __name__ == "__main__":
    print("Setting up DRI Intelligence database...")
    setup_database()
    load_demo_data()
